Signup frontend and backend connected
QuirkoTech/PostmanExpress pull request #61
Opened 2023-11-10 18:48 UTC by Matheus-OAMK

2023-11-10 22:53 UTC, RepoRover requested changes
I checked your code, a few notices, I see you change API response json field called "status" to "message". The problem is that I have it everywhere called "status", organisation API, consumer API, driver API, so the change in one function only is not acceptable. I need to know the reason for this change, if axios overwrites data.status with the status code, okay, but I believe that data object in response is the actual data I send from the API. Okay, then lets come to a cookie setting part, I found out that cookie configurations were wrong in first place, in branch called consumer-logout-api, before merging to main branch I would suggest you to merge your branch with changes I made to consumer API, so cookies set correctly. 

Some notices: after merging my branch with yours, check .env.example file, some new content there. And check in /consumer_app/server/frontend-test folder. Two examples of how to request login, and logout, but signup would be the same as login. Very important notice is "credentials": "include" even in login and signup requests, without it you wound. be able to get an access_token cookie.

2023-11-11 00:19 UTC, Matheus-OAMK commented
The two other responses I got were sent as a "message" such as email already exists etc. So to make things consistent I changed it from status to message.

2023-11-11 12:49 UTC, Matheus-OAMK commented
Okay, I will adjust the code accordingly.

2023-11-12 19:09 UTC, RepoRover approved these changes

2023-11-12 19:09 UTC, merged